package dev.janssensoftware.memento;

import dev.janssensoftware.memento.infrastructure.auth.in.web.dto.AuthResponseDto;
import dev.janssensoftware.memento.infrastructure.auth.in.web.dto.RegisterRequestDto;
import dev.janssensoftware.memento.infrastructure.note.in.web.dto.WebNoteDto;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.http.*;
import org.springframework.test.annotation.DirtiesContext;

import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@Import(TestcontainersConfiguration.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
public class NoteControllerIntegrationTest {

    @Autowired
    private TestRestTemplate restTemplate;

    private String authToken;
    private static final String TEST_USERNAME = "testuser";
    private static final String TEST_PASSWORD = "password123";

    @BeforeEach
    public void setup() {
        // Register a user
        RegisterRequestDto registerRequest = new RegisterRequestDto();
        registerRequest.setUsername(TEST_USERNAME);
        registerRequest.setPassword(TEST_PASSWORD);

        ResponseEntity<AuthResponseDto> response = restTemplate.postForEntity(
                "/api/auth/register",
                registerRequest,
                AuthResponseDto.class
        );

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        authToken = response.getBody().getToken();
    }

    @Test
    public void testCreateNote() {
        // Arrange
        WebNoteDto noteDto = new WebNoteDto(
                null, // ID will be generated by the server
                "Test note content",
                200, // width
                150, // height
                10,  // x
                20,  // y
                "#FF0000FF" // RGBA color (red with full opacity)
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(authToken);
        HttpEntity<WebNoteDto> request = new HttpEntity<>(noteDto, headers);

        // Act
        ResponseEntity<WebNoteDto> response = restTemplate.exchange(
                "/api/notes",
                HttpMethod.POST,
                request,
                WebNoteDto.class
        );

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().id()).isNotNull();
        assertThat(response.getBody().content()).isEqualTo("Test note content");
        assertThat(response.getBody().width()).isEqualTo(200);
        assertThat(response.getBody().height()).isEqualTo(150);
        assertThat(response.getBody().x()).isEqualTo(10);
        assertThat(response.getBody().y()).isEqualTo(20);
        assertThat(response.getBody().rgbaColor()).isEqualTo("#FF0000FF");
    }

    @Test
    public void testCreateNoteWithInvalidColor() {
        // Arrange
        WebNoteDto noteDto = new WebNoteDto(
                null,
                "Test note content",
                200,
                150,
                10,
                20,
                "invalid-color" // Invalid color format
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(authToken);
        HttpEntity<WebNoteDto> request = new HttpEntity<>(noteDto, headers);

        // Act
        ResponseEntity<String> response = restTemplate.exchange(
                "/api/notes",
                HttpMethod.POST,
                request,
                String.class
        );

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.INTERNAL_SERVER_ERROR);
    }

    @Test
    public void testCreateNoteWithoutAuthentication() {
        // Arrange
        WebNoteDto noteDto = new WebNoteDto(
                null,
                "Test note content",
                200,
                150,
                10,
                20,
                "#FF0000FF"
        );

        // Act - No auth token provided
        ResponseEntity<String> response = restTemplate.postForEntity(
                "/api/notes",
                noteDto,
                String.class
        );

        // Assert
        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    public void testUpdateNote() {
        // Arrange - First create a note
        WebNoteDto noteDto = new WebNoteDto(
                null,
                "Test note content",
                200,
                150,
                10,
                20,
                "#FF0000FF"
        );

        HttpHeaders headers = new HttpHeaders();
        headers.setBearerAuth(authToken);
        HttpEntity<WebNoteDto> createRequest = new HttpEntity<>(noteDto, headers);

        ResponseEntity<WebNoteDto> createResponse = restTemplate.exchange(
                "/api/notes",
                HttpMethod.POST,
                createRequest,
                WebNoteDto.class
        );

        assertThat(createResponse.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(createResponse.getBody()).isNotNull();
        UUID noteId = createResponse.getBody().id();

        // Now update the note
        WebNoteDto updatedNoteDto = new WebNoteDto(
                noteId,
                "Updated content",
                300, // changed width
                250, // changed height
                30,  // changed x
                40,  // changed y
                "#00FF00FF" // changed color
        );

        List<WebNoteDto> notesToUpdate = List.of(updatedNoteDto);
        HttpEntity<List<WebNoteDto>> updateRequest = new HttpEntity<>(notesToUpdate, headers);

        // Act
        ResponseEntity<List<WebNoteDto>> updateResponse = restTemplate.exchange(
                "/api/notes",
                HttpMethod.PATCH,
                updateRequest,
                new ParameterizedTypeReference<>() {
                }
        );

        // Assert
        assertThat(updateResponse.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(updateResponse.getBody()).isNotNull();
        assertThat(updateResponse.getBody().size()).isEqualTo(1);

        WebNoteDto updatedNote = updateResponse.getBody().getFirst();
        assertThat(updatedNote.id()).isEqualTo(noteId);
        assertThat(updatedNote.content()).isEqualTo("Updated content");
        assertThat(updatedNote.width()).isEqualTo(300);
        assertThat(updatedNote.height()).isEqualTo(250);
        assertThat(updatedNote.x()).isEqualTo(30);
        assertThat(updatedNote.y()).isEqualTo(40);
        assertThat(updatedNote.rgbaColor()).isEqualTo("#00FF00FF");

        // Verify the note was actually updated in the database by fetching it again
        ResponseEntity<WebNoteDto> getResponse = restTemplate.exchange(
                "/api/notes/" + noteId,
                HttpMethod.GET,
                new HttpEntity<>(headers),
                WebNoteDto.class
        );

        assertThat(getResponse.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(getResponse.getBody()).isNotNull();
        assertThat(getResponse.getBody().id()).isEqualTo(noteId);
        assertThat(getResponse.getBody().content()).isEqualTo("Updated content");
        assertThat(getResponse.getBody().width()).isEqualTo(300);
        assertThat(getResponse.getBody().height()).isEqualTo(250);
        assertThat(getResponse.getBody().x()).isEqualTo(30);
        assertThat(getResponse.getBody().y()).isEqualTo(40);
        assertThat(getResponse.getBody().rgbaColor()).isEqualTo("#00FF00FF");
    }
}
